### ISSUE TITLE
Upgrade naar java 8

### ISSUE THREAD

**Issue by mprins** [B3Partners/datastorelinker.old#11]
oa. update van GeoTools 18, Quartz enz,enz. libraries

- [x] upgrade commons-mail-b3p B3Partners/commons-mail-b3p#1
- [x] upgrade b3p-commons-core B3Partners/b3p-commons-core#2
- [x] upgrade b3p-commons-gis B3Partners/b3p-commons-gis#1
- [x] upgrade b3p-gt2-csv B3Partners/b3p-gt2-csv#1
- [x] upgrade b3p-gt2-dxf B3Partners/b3p-gt2-dxf#1
- [ ] upgrade b3p-gt2-msaccess B3Partners/b3p-gt2-msaccess#1
- [x] upgrade b3p-gt2-ogr B3Partners/b3p-gt2-ogr#1
- [x] upgrade b3p-gt2-sdl B3Partners/b3p-gt2-sdl#1
- [x] upgrade b3p-gt2-suf2 B3Partners/b3p-gt2-suf2#1
- [x] upgrade b3p-suf2-reader B3Partners/b3p-suf2-reader#1
- [x] upgrade b3p-mapfile B3Partners/b3p-mapfile#1
- [x] upgrade jump-b3p B3Partners/jump-b3p#1
- [x] upgrade securityfilter-b3p B3Partners/securityfilter-b3p#1
- [x] upgrade datastorelinkerEntities B3Partners/datastorelinkerEntities#4
- [x] upgrade b3p-datastorelinker B3Partners/b3p-datastorelinker#5
- [ ] upgrade datastorelinker  #11

**Comment by mprins** [comment]
vanwege de upgrade van Quartz moeten de tabellen bijgewerkt worden, zie: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/migration-guide.html#making-changes-for-setups-using-jdbcjobstore

**Comment by mprins** [comment]
quick tests:
- [x] PG tabel transformeren werkt (PG -> PG)
- [ ] Database tabel transformeren werkt (oracle -> PG)
- [ ] Database tabel transformeren werkt (PG -> oracle)
- [ ] Oracle tabel transformeren werkt (oracle -> oracle)
- [x] shapefile handmatig transformeren werkt
- [x] shapefile automatisch transformeren werkt
- [x] dxf handmatig transformeren werkt
- [x] dxf automatisch transformeren werkt
- [x] csv handmatig transformeren werkt
- [x] csv automatisch transformeren werkt (zowel met als zonder geometrie in csv)
- [x] mail notificatie versturen werken
